###########################################################################################################
# Service Registry Stack
# HA Service discovery, health checks, load-balancing,
# DNS name lookup, routing intentions, KV store,
# DNS Server, Secret Store/Vault
###########################################################################################################
version: "3.8"

volumes:
  data_volume:

networks:
  admin_network:
    external: true

configs:
  common_config:
    file: /mnt/config/common.json
  client_config:
    file: /mnt/config/client.json
  server_config:
    file: /mnt/config/server.json

secrets:
  ca_file:
    file: /mnt/certs/ca.crt
  cert_file:
    file: /mnt/certs/cert.crt
  key_file:
    file: /mnt/certs/tls.key

services:
  consul:
    image: consul:${CONSUL_VERSION:-latest}
    entrypoint: /usr/local/scripts/consul-entrypoint.sh
    command: agent
    configs:
      - source: common_config
        target: /consul/data/bootstrap/common.json
      - source: client_config
        target: /consul/data/bootstrap/client.json
      - source: server_config
        target: /consul/data/bootstrap/server.json
    secrets:
      - source: ca_file
        target: /consul/data/certs/ca.crt
      - source: cert_file
        target: /consul/data/certs/cert.crt
      - source: key_file
        target: /consul/data/certs/tls.key
    volumes:
      - data_volume:/consul/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/scripts:/usr/local/scripts:rw
      - /mnt/backups:/consul/backups:rw
    env_file:
      - /mnt/scripts/consul.env
    networks:
        admin_network:
          aliases:
            - consul.service.consul
    #healthcheck:
      #test: ['CMD', '/bin/sh', '-c', 'curl -sfLo /dev/null http://127.0.0.1:8500/v1/health/node/$$HOSTNAME']
    deploy:
      endpoint_mode: dnsrr
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

  registrator:
    image: gliderlabs/registrator:master
    command: -internal consul://consul.service.consul:8500
    env_file:
      - /mnt/scripts/consul.env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      admin_network: {}
    deploy:
      mode: global
