###########################################################################################################
# Service Registry Stack
# HA Service discovery, health checks, load-balancing,
# DNS name lookup, routing intentions, KV store,
# DNS Server, Secret Store/Vault
###########################################################################################################
version: "3.8"

volumes:
  data_volume:

networks:
  admin_network:
    external: true

configs:
  common_config:
    file: ./config/common.json
  client_config:
    file: ./config/client.json
  server_config:
    file: ./config/server.json

services:
  consul:
    image: consul:${CONSUL_VERSION:-latest}
    entrypoint: /usr/local/scripts/startup-script.sh
    command: agent
    configs:
      - source: common_config
        target: /consul/data/bootstrap/common.json
      - source: client_config
        target: /consul/data/bootstrap/client.json
      - source: server_config
        target: /consul/data/bootstrap/server.json
    volumes:
      - data_volume:/consul/data
      - ./scripts:/usr/local/scripts
    ports:
      - target: 8500
        published: 8500
        mode: host
    networks:
      admin_network:
        aliases:
          - consul.service.consul
    env_file:
      - ./scripts/consul.env
    environment:
      - NUM_OF_MGR_NODES
      - NODE_IP
      - NODE_ID
      - NODE_NAME
      - NODE_IS_MANAGER
    healthcheck:
      test: ['CMD', '/bin/sh', '-c', 'curl -sfLo /dev/null http://127.0.0.1:8500/v1/health/node/$$HOSTNAME']
    deploy:
      endpoint_mode: dnsrr
      mode: global
      restart_policy:
        condition: none
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

  registrator:
    image: gliderlabs/registrator:master
    command: -internal consul://consul.service.consul:8500
    env_file:
      - ./scripts/consul.env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      admin_network: {}
    deploy:
      mode: global
