###########################################################################################################
# Core Stack
# HA Service discovery, health checks, load-balancing,
# DNS name lookup, routing intentions, KV store,
# DNS Server, Secret Store/Vault
###########################################################################################################
version: "3.8"

###########################################################################################################
volumes:
  consul_data:

###########################################################################################################
networks:
  admin_network:
    external: true

###########################################################################################################
configs:
  consul_common:
    file: /mnt/config/consul-common-template.json
  consul_client:
    file: /mnt/config/consul-client-template.json
  consul_server:
    file: /mnt/config/consul-server-template.json
  dns:
    file: /mnt/config/dns-dnsmasq-template.conf
  vault:
    file: /mnt/config/vault-server-template.json

###########################################################################################################
secrets:
  consul_ca:
    file: /mnt/certs/consul-agent-ca.pem
  consul_server_cert:
    file: /mnt/certs/docker-server-consul-0.pem
  consul_server_key:
    file: /mnt/certs/docker-server-consul-0-key.pem
  consul_client_cert:
    file: /mnt/certs/docker-client-consul-0.pem
  consul_client_key:
    file: /mnt/certs/docker-client-consul-0-key.pem

###########################################################################################################
services:
  consul:
    image: consul:${CONSUL_VERSION:-latest}
    init: true
    entrypoint: /usr/local/scripts/consul-entrypoint.sh
    command: agent
    configs:
      - source: consul_common
        target: /consul/data/bootstrap/common.json
      - source: consul_client
        target: /consul/data/bootstrap/client.json
      - source: consul_server
        target: /consul/data/bootstrap/server.json
    secrets:
      - source: consul_ca
        target: /consul/data/certs/consul-agent-ca.pem
      - source: consul_server_cert
        target: /consul/data/certs/docker-server-consul-0.pem
      - source: consul_server_key
        target: /consul/data/certs/docker-server-consul-0-key.pem
      - source: consul_client_cert
        target: /consul/data/certs/docker-client-consul-0.pem
      - source: consul_client_key
        target: /consul/data/certs/docker-client-consul-0-key.pem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - consul_data:/consul/data
      - /mnt/scripts:/usr/local/scripts:rw
      - /mnt/backups:/consul/backups:rw
    env_file:
      - /mnt/scripts/core.env
    networks:
        admin_network:
          aliases:
            - consul.service.consul
    deploy:
      endpoint_mode: dnsrr
      mode: global

###########################################################################################################
  dns:
    image: storytel/dnsmasq
    init: true
    command: /usr/local/scripts/dns-entrypoint.sh
    depends_on:
     - consul
    init: true
    configs:
      - source: dns
        target: /etc/templates/dnsmasq.conf
    env_file:
      - /mnt/scripts/core.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/scripts:/usr/local/scripts:rw
    cap_add:
      - NET_ADMIN
    networks:
      admin_network:
        aliases:
          - dns.service.consul
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 1s
        order: stop-first

###########################################################################################################
  registrator:
    image: gliderlabs/registrator:master
    init: true
    depends_on:
       - consul
       - dns
    command: -cleanup -internal consul://consul.service.consul:8500
    env_file:
      - /mnt/scripts/core.env
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - admin_network
    deploy:
      mode: global
    dns:
      - dns.service.consul

###########################################################################################################
  vault:
    image: 'vault'
    init: true
    entrypoint: /usr/local/scripts/vault-entrypoint.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/scripts:/usr/local/scripts:rw
    configs:
      - source: vault
        target: /vault/templates/vault.json
    env_file:
      - /mnt/scripts/core.env
    cap_add:
      - IPC_LOCK
    networks:
      - admin_network
    dns:
      - dns.service.consul
    depends_on:
      - consul
      - dns
