#####################################################
# DevOps Stack - Used to manage dev-ops stuff like Docker
#####################################################
# External Ports
# 1080:host/tcp     = proxy - SOCKS4/SOCKS5 proxy server
# 9000:ingress/tcp  = web - HTTP UI
# 9001:host/tcp:udp = agent - HTTP REST

version: '3.8'

services:
  web:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - web_volume:/data
    networks:
      - agent_network
      - admin_network
    deploy:
      replicas: 1

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - agent_network
      - admin_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  proxy:
    image: wernight/dante
    ports:
      - 1080:1080
    networks:
     - admin_network
    deploy:
      replicas: 1

volumes:
  web_volume:
  registry_volumne:

networks:
  agent_network:
    driver: overlay
    attachable: true
  admin_network:
    external: true
