#####################################################
# DevOps Stack - Used to manage dev-ops stuff like Docker
#####################################################
# External Ports
# 9000:ingress/tcp      = web - HTTP UI
# 9001:host/tcp:udp     = agent - HTTP REST

version: '3.8'

networks:
  admin_network:
    external: true

volumes:
  web_volume:
  proxy_cache:

services:
  web:
    image: portainer/portainer
    volumes:
      - /mnt/webmgr:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9000:9000
    networks:
     - admin_network
    deploy:
      placement:
        constraints: [node.platform.os == linux]

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
     - admin_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

