#####################################################
# Diagnostics Stack - Used for debugging and troubleshooting
#####################################################
# External Ports
# 1080/tcp:udp = proxy:SOCKS4/SOCKS5 Proxy Server
# 3128/tcp     = proxy:HTTP/HTTPS/FTP Proxy Server

version: '3.7'

volumes:
  proxy_cache:

networks:
  admin_network:
    external: true

services:
  socks-proxy:
    image: wernight/dante
    ports:
      - 1080:1080
    networks:
     - admin_network
    deploy:
      replicas: 1

  http-proxy:
    image: sameersbn/squid:3.5.27-2
    ports:
      - 3128:3128
    networks:
     - admin_network
    volumes:
      - proxy_cache:/var/spool/squid
    deploy:
      replicas: 1

  jump-box:
    image: alpine
    entrypoint: /usr/local/scripts/jump-box-entrypoint.sh
    env_file:
    - /mnt/scripts/core.env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/backups:/usr/share/nginx/html:rw
    - /mnt/scripts:/usr/local/scripts
    networks:
      - admin_network
    deploy:
      replicas: 1

