#####################################################
# Diagnostics Stack - Used for debugging and troubleshooting
#####################################################
# External Ports
# 3128/tcp     = proxy:HTTP/HTTPS/FTP Proxy Server

version: '3.8'

volumes:
  proxy_volume:

networks:
  admin_network:
    external: true

services:
 #####################################################
  # SOCKS4 / SOCKS5 Proxy Server
  proxy:
    image: wernight/dante
    ports:
      - '1080:1080'
    dns:
      - 192.168.1.2
      - 192.168.1.3
    networks:
      - admin_network
    deploy:
      replicas: 1

