###########################################################################################################
# Diagnostics Stack - Used for debugging and troubleshooting
###########################################################################################################
# External Ports
# 1080/tcp:udp = socks-proxy1:SOCKS4/SOCKS5 Proxy Server
# 3128/tcp     = http-proxy:HTTP/HTTPS/FTP Proxy Server
# 8080/tcp:udp = socks-proxy2:SOCKS4/SOCKS5 Proxy Server

version: '3.7'

volumes:
  proxy_cache:

networks:
  admin_network:
    external: true

services:
  socks-proxy1:
    image: wernight/dante
    ports:
      - 1080:1080
    networks:
     - admin_network
    dns:
      - dns.service.consul

  socks-proxy2:
    # socks5 proxy service for browsers to connect into the network
    # https://github.com/serjs/socks5-server
    image: serjs/go-socks5-proxy
    init: true
    ports:
      -8080:1080
    networks:
      - admin_network
    dns:
      - dns.service.consul

  http-proxy:
    image: sameersbn/squid:3.5.27-2
    ports:
      - 3128:3128
    networks:
     - admin_network
    volumes:
      - proxy_cache:/var/spool/squid
    dns:
      - dns.service.consul

  jump-box:
    image: alpine
    entrypoint: /usr/local/scripts/jump-box-entrypoint.sh
    env_file:
    - /mnt/scripts/core.env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /mnt/backups:/usr/share/nginx/html:rw
    - /mnt/scripts:/usr/local/scripts
    networks:
      - admin_network
    dns:
      - dns.service.consul

