#####################################################
# Logging Stack
# Mongo DB, Elastic Search, Log Agent,  & Graylog
#####################################################
# External Ports
# 12201/udp    = web:GELF

# Internal Ports
# 1514/tcp:udp = web:Syslog
# 5555/tcp:udp = web:RawPlainText
# 9000/tcp     = web:HTTP Web UI and REST API
# 9200/        = api:HTTPS
# 9300/tcp     = api:HTTP
# 12201/tcp    = web:GELF
# 12301/tpc:udp= web:Nginx Syslog activity
# 12302/tpc:udp= web:Nginx Syslog error
# 27017/tcp    = db:MongoDB

volumes:
  # Logs db (Mongo) persistence
  logs_db_volume:

  # Logs API (ElasticSearch) persistence
  logs_api_volume:

  # Logs web (Graylog) persistence
  logs_web_volume:

networks:
  # Access to logs db, agent, API, and web services
  log_network:
    external: true

  # Access to all services
  admin_network:
    external: true

  # Access to all API
  api_network:
    external: true

version: '3.8'

services:

  #####################################################
  agent:
  # LogAgent
    image: sematext/logagent:latest
    depends_on:
      - api
    environment:
        # The index where the agent should log to (for Sematext Cloud users the logs token)
        LOGS_TOKEN: 177434fe-0862-43e4-a162-de767c346723
        # Sematext Cloud region US or EU (default: US). The receiver URL will be set to EU/US default values. When using REGION, you don't need to set LOGS_RECEIVER_URL #- REGION=US
        # The URL of your Elasticsearch Endpoint (defaults to Sematext Cloud US https://logsene-receiver.sematext.com).
        LOGS_RECEIVER_URL: http://elasticsearch:9200
        # Semicolon-separated list of file globs
        LOG_GLOB: /mylogs//*.log;/var/log//*.log;/var/log/**/*.log
        # Additional command line arguments for Logagent
        #LOGAGENT_ARGS: "-n httpd"
    cap_add:
        - SYS_ADMIN
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /var/log:/mylogs
    networks:
        log_network:
          aliases:
            - logagent
        admin_network: {}
    dns:
     - dns.service.consul

  #####################################################
  db:
  # MongoDB
    image: mongo:4.2
    volumes:
      - logs_db_volume:/data/db
    networks:
      admin_network: {}
      log_network:
        aliases:
            - mongo
    dns:
     - dns.service.consul

  #####################################################
  api:
  # ElasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    depends_on:
       - db
    environment:
      http.host: 0.0.0.0
      network.bind_host: 0.0.0.0
      transport.host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - logs_api_volume:/usr/share/elasticsearch/data
    networks:
      admin_network: {}
      log_network:
        aliases:
          - elasticsearch
    dns:
     - dns.service.consul

  #####################################################
  web:
  # Graylog
    image: graylog/graylog:4.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: eventmanagersecret
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://ip172-18-0-58-c046nor6hnp000cgumdg-9003.direct.labs.play-with-docker.com/
    depends_on:
      - api
    volumes:
      - logs_web_volume:/usr/share/graylog/data
    networks:
     admin_network: {}
     api_network: {}
     log_network:
        aliases:
          - graylog
    dns:
     - dns.service.consul
