version: '3.7'

networks:
  admin_network:
    external: true

volumes:
  data:

services:
  server:
    image: itsthenetwork/nfs-server-alpine:12
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - data:/data
    cap_add:
      - ALL
    networks:
      admin_network:
        aliases:
          - nfs_server.service.consul
    deploy:
      replicas: 1
