version: '3.7'

networks:
  admin_network:
    external: true

volumes:
  test:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfsserver_storage,rw
      device: ":/data"

x-nfstest:
  &nfstest-base
  image: alpine
  volumes:
    - type: volume
      source: test
      target: /data
      volume:
        nocopy: true
  networks:
    - admin_network
  deploy:
    replicas: 1

services:
  #####################################################
  producer:
    << : *nfstest-base
    command:  |
      /bin/sh -c "
        while true;
          do touch /data/hello-from-producer;
          echo '/data/hello-from-producer written';
          sleep 5;
          rm /data/hello-from-producer;
          echo '/data/hello-from-producer deleted';
          sleep 5;
        done
      "

  #####################################################
  consumer:
    << : *nfstest-base
    command :  |
      /bin/sh -c "
        while  true; do ls -al /data/;  sleep  1;  done
      "

  #####################################################
  client:
    image: alpine
    networks:
      - admin_network
    deploy:
      replicas: 1
    command :  |
        /bin/sh -c "
          apk update
          apk add \
              curl \
              jq \
              openssl \
              gettext \
              iputils \
              nfs-utils \
              iproute2
          mount -v -o vers=4,loud nfsserver_storage:/ /data
          df -h
          touch /data/file.txt
          ls /data
        "
