version: '3.7'

networks:
  admin_network:
    external: true

services:
  storage:
    image: itsthenetwork/nfs-server-alpine
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /mnt/nfssvr:/data
    cap_add:
      - ALL
    ports:
      - 2049:2049
    networks:
      admin_network:
        ipv4_address: 192.168.100.100
        aliases:
          - nfs_server.service.consul
    deploy:
      replicas: 1
