version: '3.7'

volumes:
  storage_volume:

networks:
  admin_network:
    external: true

services:
  storage:
    image: itsthenetwork/nfs-server-alpine
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - storage_volume:/data
    cap_add:
      - ALL
    ports:
      - 2049:2049
    networks:
      - admin_network
    deploy:
      replicas: 1
