version: '3.7'

networks:
  admin_network:
    external: true

volumes:
  data:
  test:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs-server,rw
      device: ":/data"

x-nfstest:
  &nfstest-base
  image: nfstest
  volumes:
    - type: volume
      source: test
      target: /data
      volume:
        nocopy: true
  networks:
    - admin_network
  deploy:
    replicas: 1

services:
  #####################################################
  producer:
    << : *nfstest-base
    command:  |
      /bin/sh -c "
        while true;
          do touch /data/hello-from-producer;
          echo '/data/hello-from-producer written';
          sleep 5;
          rm /data/hello-from-producer;
          echo '/data/hello-from-producer deleted';
          sleep 5;
        done
      "

  #####################################################
  consumer:
    << : *nfstest-base
    command :  |
      /bin/sh -c "
        while  true; do ls -al /data/;  sleep  1;  done
      "

  #####################################################
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:12
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - data:/data
    cap_add:
      - ALL
    networks:
      admin_network:
        aliases:
          - nfs-server.service.consul
    deploy:
      replicas: 1
